FROM tensorflow/tensorflow:latest-gpu
MAINTAINER Bill Xue <xueeinstein@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# built-in packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common curl \
    && sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/arc-theme.list" \
    && curl -SL http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key | apt-key add - \
    && add-apt-repository ppa:fcwu-tw/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends --allow-unauthenticated \
        supervisor \
        openssh-server pwgen sudo vim-tiny \
        net-tools \
        lxde x11vnc xvfb \
        gtk2-engines-murrine ttf-ubuntu-font-family \
        firefox htop nginx \
        fonts-wqy-microhei \
        language-pack-zh-hant language-pack-gnome-zh-hant firefox-locale-zh-hant \
        python-pip python-dev build-essential \
        mesa-utils libgl1-mesa-dri \
        gnome-themes-standard gtk2-engines-pixbuf gtk2-engines-murrine pinta arc-theme \
        dbus-x11 x11-utils \
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# tini for subreap
ENV TINI_VERSION v0.9.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /bin/tini
RUN chmod +x /bin/tini

# install deps for web VNC
ADD image /
RUN pip install setuptools wheel && pip install -r /usr/lib/web/requirements.txt

# install bazel and DeepMind Lab deps
RUN apt-get update && apt-get install -y openjdk-8-jdk && \
    echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    curl https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
    apt-get update && apt-get install -y bazel && \
    apt-get install -y lua5.1 liblua5.1-0-dev libffi-dev gettext git zip \
    freeglut3-dev libsdl2-dev libosmesa6-dev python-dev python-numpy realpath && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -r /var/lib/apt/lists/* /root/.cache/pip/

# build DeepMind Lab
RUN git clone https://github.com/deepmind/lab /root/lab && cd /root/lab && \
    bazel build :deepmind_lab.so --define headless=glx
WORKDIR /root/lab

# Jupyter Notebook
EXPOSE 8888
# TensorBoard
EXPOSE 6006
# Web VNC
EXPOSE 80

ENV HOME=/home/ubuntu \
    SHELL=/bin/bash
ENTRYPOINT ["/startup.sh"]