FROM tensorflow/tensorflow:latest-gpu
MAINTAINER Bill Xue <xueeinstein@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# built-in packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends software-properties-common curl \
    && sh -c "echo 'deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/arc-theme.list" \
    && curl -SL http://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key | apt-key add - \
    && add-apt-repository ppa:fcwu-tw/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends --allow-unauthenticated \
        supervisor \
        openssh-server pwgen sudo vim-tiny \
        net-tools \
        lxde x11vnc xvfb \
        gtk2-engines-murrine ttf-ubuntu-font-family \
        firefox htop nginx \
        fonts-wqy-microhei \
        language-pack-zh-hant language-pack-gnome-zh-hant firefox-locale-zh-hant \
        python-pip python-dev build-essential \
        mesa-utils libgl1-mesa-dri \
        gnome-themes-standard gtk2-engines-pixbuf gtk2-engines-murrine pinta arc-theme \
        dbus-x11 x11-utils \
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# tini for subreap
ENV TINI_VERSION v0.9.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /bin/tini
RUN chmod +x /bin/tini

# install deps for web VNC
ADD image /
RUN pip install setuptools wheel && pip install -r /usr/lib/web/requirements.txt

# install gym
RUN apt-get update && \
    apt-get -y install zlib1g python3-pip python3-opengl python3-numpy xautomation \
            git ffmpeg libsdl2-2.0-0 libboost-python1.58.0 libboost-thread1.58.0 \
            libboost-filesystem1.58.0 libboost-system1.58.0 fluidsynth build-essential \
            swig python-dev cmake zlib1g-dev libsdl2-dev libboost-all-dev wget unzip && \
    pip3 --no-cache-dir install --upgrade 'gym[all]'

# build torcs
RUN git clone https://github.com/ugo-nama-kun/gym_torcs.git /root/gym_torcs && \
    cd /root/gym_torcs/vtorcs-RL-color && \
    apt-get install -y libglib2.0-dev  libgl1-mesa-dev libglu1-mesa-dev  freeglut3-dev \
            libplib-dev  libopenal-dev libalut-dev libxi-dev libxmu-dev libxrender-dev \
            libxrandr-dev libpng12-dev && \
    ./configure && make && make install && make datainstall && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -r /var/lib/apt/lists/* /root/.cache/pip/

# Jupyter Notebook
EXPOSE 8888
# TensorBoard
EXPOSE 6006
# Web VNC
EXPOSE 80

WORKDIR /root
ENV HOME=/home/ubuntu \
    SHELL=/bin/bash
ENTRYPOINT ["/startup.sh"]